# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sdr_oran_pb2 as sdr__oran__pb2


class IQStreamServiceStub(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    SDR IQ Sample Streaming Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamIQ = channel.stream_stream(
                '/sdr.oran.IQStreamService/StreamIQ',
                request_serializer=sdr__oran__pb2.IQSampleBatch.SerializeToString,
                response_deserializer=sdr__oran__pb2.IQAck.FromString,
                )
        self.GetStreamStats = channel.unary_unary(
                '/sdr.oran.IQStreamService/GetStreamStats',
                request_serializer=sdr__oran__pb2.StreamStatsRequest.SerializeToString,
                response_deserializer=sdr__oran__pb2.StreamStatsResponse.FromString,
                )
        self.StartStream = channel.unary_unary(
                '/sdr.oran.IQStreamService/StartStream',
                request_serializer=sdr__oran__pb2.StreamConfig.SerializeToString,
                response_deserializer=sdr__oran__pb2.StreamResponse.FromString,
                )
        self.StopStream = channel.unary_unary(
                '/sdr.oran.IQStreamService/StopStream',
                request_serializer=sdr__oran__pb2.StreamStopRequest.SerializeToString,
                response_deserializer=sdr__oran__pb2.StreamResponse.FromString,
                )
        self.UpdateDoppler = channel.unary_unary(
                '/sdr.oran.IQStreamService/UpdateDoppler',
                request_serializer=sdr__oran__pb2.DopplerUpdate.SerializeToString,
                response_deserializer=sdr__oran__pb2.StreamResponse.FromString,
                )


class IQStreamServiceServicer(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    SDR IQ Sample Streaming Service
    """

    def StreamIQ(self, request_iterator, context):
        """Bidirectional streaming for real-time IQ samples
        SDR → O-RAN DU (uplink path from satellite)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamStats(self, request, context):
        """Get current stream statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStream(self, request, context):
        """Control commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDoppler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IQStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamIQ': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamIQ,
                    request_deserializer=sdr__oran__pb2.IQSampleBatch.FromString,
                    response_serializer=sdr__oran__pb2.IQAck.SerializeToString,
            ),
            'GetStreamStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamStats,
                    request_deserializer=sdr__oran__pb2.StreamStatsRequest.FromString,
                    response_serializer=sdr__oran__pb2.StreamStatsResponse.SerializeToString,
            ),
            'StartStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=sdr__oran__pb2.StreamConfig.FromString,
                    response_serializer=sdr__oran__pb2.StreamResponse.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=sdr__oran__pb2.StreamStopRequest.FromString,
                    response_serializer=sdr__oran__pb2.StreamResponse.SerializeToString,
            ),
            'UpdateDoppler': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDoppler,
                    request_deserializer=sdr__oran__pb2.DopplerUpdate.FromString,
                    response_serializer=sdr__oran__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdr.oran.IQStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IQStreamService(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    SDR IQ Sample Streaming Service
    """

    @staticmethod
    def StreamIQ(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sdr.oran.IQStreamService/StreamIQ',
            sdr__oran__pb2.IQSampleBatch.SerializeToString,
            sdr__oran__pb2.IQAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStreamStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.IQStreamService/GetStreamStats',
            sdr__oran__pb2.StreamStatsRequest.SerializeToString,
            sdr__oran__pb2.StreamStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.IQStreamService/StartStream',
            sdr__oran__pb2.StreamConfig.SerializeToString,
            sdr__oran__pb2.StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.IQStreamService/StopStream',
            sdr__oran__pb2.StreamStopRequest.SerializeToString,
            sdr__oran__pb2.StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDoppler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.IQStreamService/UpdateDoppler',
            sdr__oran__pb2.DopplerUpdate.SerializeToString,
            sdr__oran__pb2.StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SpectrumMonitorServiceStub(object):
    """Spectrum Monitoring Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSpectrum = channel.unary_unary(
                '/sdr.oran.SpectrumMonitorService/GetSpectrum',
                request_serializer=sdr__oran__pb2.SpectrumRequest.SerializeToString,
                response_deserializer=sdr__oran__pb2.SpectrumData.FromString,
                )
        self.StreamSpectrum = channel.unary_stream(
                '/sdr.oran.SpectrumMonitorService/StreamSpectrum',
                request_serializer=sdr__oran__pb2.SpectrumRequest.SerializeToString,
                response_deserializer=sdr__oran__pb2.SpectrumData.FromString,
                )


class SpectrumMonitorServiceServicer(object):
    """Spectrum Monitoring Service
    """

    def GetSpectrum(self, request, context):
        """Request spectrum data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSpectrum(self, request, context):
        """Stream spectrum updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpectrumMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSpectrum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpectrum,
                    request_deserializer=sdr__oran__pb2.SpectrumRequest.FromString,
                    response_serializer=sdr__oran__pb2.SpectrumData.SerializeToString,
            ),
            'StreamSpectrum': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSpectrum,
                    request_deserializer=sdr__oran__pb2.SpectrumRequest.FromString,
                    response_serializer=sdr__oran__pb2.SpectrumData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdr.oran.SpectrumMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpectrumMonitorService(object):
    """Spectrum Monitoring Service
    """

    @staticmethod
    def GetSpectrum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.SpectrumMonitorService/GetSpectrum',
            sdr__oran__pb2.SpectrumRequest.SerializeToString,
            sdr__oran__pb2.SpectrumData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamSpectrum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sdr.oran.SpectrumMonitorService/StreamSpectrum',
            sdr__oran__pb2.SpectrumRequest.SerializeToString,
            sdr__oran__pb2.SpectrumData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AntennaControlServiceStub(object):
    """Antenna Control Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PointAntenna = channel.unary_unary(
                '/sdr.oran.AntennaControlService/PointAntenna',
                request_serializer=sdr__oran__pb2.AntennaPointingRequest.SerializeToString,
                response_deserializer=sdr__oran__pb2.AntennaPointingResponse.FromString,
                )
        self.GetAntennaStatus = channel.unary_unary(
                '/sdr.oran.AntennaControlService/GetAntennaStatus',
                request_serializer=sdr__oran__pb2.AntennaStatusRequest.SerializeToString,
                response_deserializer=sdr__oran__pb2.AntennaStatus.FromString,
                )
        self.TrackSatellite = channel.stream_stream(
                '/sdr.oran.AntennaControlService/TrackSatellite',
                request_serializer=sdr__oran__pb2.TrackingUpdate.SerializeToString,
                response_deserializer=sdr__oran__pb2.AntennaStatus.FromString,
                )


class AntennaControlServiceServicer(object):
    """Antenna Control Service
    """

    def PointAntenna(self, request, context):
        """Point antenna to satellite
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAntennaStatus(self, request, context):
        """Get antenna status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackSatellite(self, request_iterator, context):
        """Track satellite (continuous pointing update)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AntennaControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PointAntenna': grpc.unary_unary_rpc_method_handler(
                    servicer.PointAntenna,
                    request_deserializer=sdr__oran__pb2.AntennaPointingRequest.FromString,
                    response_serializer=sdr__oran__pb2.AntennaPointingResponse.SerializeToString,
            ),
            'GetAntennaStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAntennaStatus,
                    request_deserializer=sdr__oran__pb2.AntennaStatusRequest.FromString,
                    response_serializer=sdr__oran__pb2.AntennaStatus.SerializeToString,
            ),
            'TrackSatellite': grpc.stream_stream_rpc_method_handler(
                    servicer.TrackSatellite,
                    request_deserializer=sdr__oran__pb2.TrackingUpdate.FromString,
                    response_serializer=sdr__oran__pb2.AntennaStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdr.oran.AntennaControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AntennaControlService(object):
    """Antenna Control Service
    """

    @staticmethod
    def PointAntenna(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.AntennaControlService/PointAntenna',
            sdr__oran__pb2.AntennaPointingRequest.SerializeToString,
            sdr__oran__pb2.AntennaPointingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAntennaStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdr.oran.AntennaControlService/GetAntennaStatus',
            sdr__oran__pb2.AntennaStatusRequest.SerializeToString,
            sdr__oran__pb2.AntennaStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrackSatellite(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sdr.oran.AntennaControlService/TrackSatellite',
            sdr__oran__pb2.TrackingUpdate.SerializeToString,
            sdr__oran__pb2.AntennaStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
