# Bandit Configuration for SDR-O-RAN Platform
# Python security scanner configuration
# Version: 1.0.0

# Test IDs to skip (with justification)
skips:
  # B101: Test for use of assert - OK in test files
  - B101

  # B601: Test for shell injection (paramiko) - Reviewed and safe
  # - B601

# Test IDs to run (all by default)
tests:
  - B201  # flask_debug_true
  - B301  # pickle usage
  - B302  # marshal usage
  - B303  # MD5 usage
  - B304  # SHA1 usage (use SHA256+)
  - B305  # cipher usage without mode
  - B306  # mktemp usage
  - B307  # eval usage
  - B308  # mark_safe usage
  - B309  # HTTPSConnection
  - B310  # urllib usage
  - B311  # random usage (use secrets module)
  - B312  # telnetlib usage
  - B313  # xml_bad_cElementTree
  - B314  # xml_bad_ElementTree
  - B315  # xml_bad_expatreader
  - B316  # xml_bad_expatbuilder
  - B317  # xml_bad_sax
  - B318  # xml_bad_minidom
  - B319  # xml_bad_pulldom
  - B320  # xml_bad_etree
  - B321  # ftplib usage
  - B322  # input usage
  - B323  # unverified_context
  - B324  # hashlib usage
  - B401  # import_telnetlib
  - B402  # import_ftplib
  - B403  # import_pickle
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xml_sax
  - B407  # import_xml_expatreader
  - B408  # import_xml_expatbuilder
  - B409  # import_xml_minidom
  - B410  # import_lxml
  - B411  # import_xmlrpclib
  - B412  # import_httpoxy
  - B413  # import_pycrypto
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # weak_cryptographic_key
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B601  # paramiko_calls
  - B602  # shell_injection
  - B603  # subprocess_without_shell_equals_true
  - B604  # shell_injection
  - B605  # shell_injection
  - B606  # shell_injection
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection
  - B610  # django_extra_used
  - B611  # django_rawsql_used
  - B701  # jinja2_autoescape_false
  - B702  # use_of_mako_templates
  - B703  # django_mark_safe

# Paths to exclude from scanning
exclude_dirs:
  - /test/
  - /tests/
  - /venv/
  - /env/
  - /.venv/
  - /node_modules/
  - /.git/
  - /.cache/
  - /__pycache__/
  - /dist/
  - /build/

# Severity level
# Options: all, low, medium, high
severity: medium

# Confidence level
# Options: all, low, medium, high
confidence: high
